
tracker:
    type: ComposedTrackers
    trackers: [NeptuneTracker, SimpleTracker]
    name: 'Experiment  02 name'
    description: 'Example of using configuration file.'
    tags: ['examples', 'config']
    offline: False
    SimpleTracker:
        root_path: './logs'
        exp_id_template: 'EXAM02-{i:03}'
    NeptuneTracker:
        project: 'goodok/composed'

seed: 777

optimizer:
  type: torch.optim.Adam
  weight_decay: 0.0001
  lr: 0.6
