` http://plantuml.com/en/class-diagram

@startuml

'!define COMMENT(x) <color:grey>x</color>
!function COMMENT(x)
  <color:grey>x</color>
!endfunction


left to right direction
'top to bottom direction  'default

package "ML Trainers" <<Cloud>> {


    package "keras" {
    }


    package "pytorch-lighning" {
        package "loggers" {
            class "pl:neptune" {
            }
            hide "pl:neptune" circle
        }
    }

    package "pytorch" {
    }
}

package "Trackers" <<Cloud>> {

    header
      Variouse params, methods.
      Even for the same methods,
      arguments are differ
    endheader

    package "neptune" {
      class "neptune" {
        name : string
        project: string
        'COMMENT('Variouse params, some methods')
        'COMMENT('Even for the same methods, arguments are differ')
        init()
        log_metric(1 kind of params)
      }
      'hide "neptune" members
      hide "neptune" circle

    }

  package "MLFlow" {
      class "MLFlow" {
        name : string
        project: string
        log_metric(2 kind of params)
      }
      'hide "MLFlow" members
      hide "MLFlow" circle
}

  class "tensorboard" {
    name : string
  }
  'hide "tensorboard" members
  hide "tensorboard" circle

  class "test_tube" {
    name : string
  }
  'hide "test_tube" members
  hide "test_tube" circle
}


@enduml
