
tracker:
    type: ComposedTrackers
    trackers: [NeptuneTracker, SimpleTracker]
    name: 'Experiment  00 name'
    description: 'Example of using configuration file.'
    tags: ['examples', 'config']
    offline: True
    SimpleTracker:
        root_path: './logs'
        exp_id_template: 'EXAM00-{i:03}'
    NeptuneTracker:
        project: 'USER_NAME/PROJECT_NAME'

